In [2]:
import numpy as np

In [3]:
c=np.arange(24).reshape(2,3,4) # axis 0 is 2,axis 1 is 3,axis 3 is 4
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
c.sum(axis=0)  # sum across matrices # (2,3,4) to (3,4)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [6]:
c.sum(axis=1)  # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [7]:
c.sum(axis=(0,2))  # sum across matrices and columns

array([ 60,  92, 124])

In [8]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

(60, 92, 124)

In [10]:
a = np.array([1, 5, 3, 19, 13, 7, 3])

In [11]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a  # the original array is untouched

array([ 1,  5,  3, 19, 13,  7,  3])